removes clone repo action

diff --git a/.github/workflows/publish_operator_image_and_bundle.yaml b/.github/workflows/publish_operator_image_and_bundle.yaml
--- a/.github/workflows/publish_operator_image_and_bundle.yaml
+++ b/.github/workflows/publish_operator_image_and_bundle.yaml
@@ -275,11 +275,20 @@ jobs:
         git commit -m "[skip-ci] Update artifacts" -a
 
     - name: Clone stakater/certified-operators repository
-      uses: GuillaumeFalourd/clone-github-repo-action@v3
-      with:
-        owner: 'stakater'
-        repository: 'certified-operators'
-        access-token: ${{ secrets.STAKATER_GITHUB_TOKEN }}
+      run: |
+        if [ -z "${{ secrets.STAKATER_GITHUB_TOKEN }}" ]; then
+            git clone https://github.com/stakater/certified-operators.git
+        else
+            git clone https://${{ secrets.STAKATER_GITHUB_TOKEN }}@github.com/stakater/certified-operators.git
+        fi
+        
+        if [ -d "certified-operators" ]; then
+            echo "Cloned certified-operators repository successfully."
+            echo "Access the repository content using \"cd certified-operators\"." 
+        else
+            echo "Error: Couldn't clone certified-operators repository. Check the inputs or the PAT scope."
+            exit 1
+        fi
     
     - name: Push branch
       run: |
@@ -297,7 +306,6 @@ jobs:
         git add .
         git commit -am "Updated multi-tenant-operator to ${{ needs.publish-image.outputs.latest_tag}}"
         git push --set-upstream origin mto-${{ needs.publish-image.outputs.latest_tag}}
-        cd ..
     
     - name: Push changes
       uses: ad-m/github-push-action@master
