Updated github actions

diff --git a/.github/workflows/push_operator_image.yaml b/.github/workflows/push_operator_image.yaml
--- a/.github/workflows/push_operator_image.yaml
+++ b/.github/workflows/push_operator_image.yaml
@@ -58,6 +58,10 @@ on:
         description: "Pyxis API token to run Preflight"
         required: true
 
+      STAKATER_GITHUB_TOKEN:
+        description: "Secret to create branch in stakater/certified-operators repository"
+        required: true
+
 jobs:
   publish-image:
     name: Publish Container Image to Catalog
@@ -165,6 +169,7 @@ jobs:
     # Build and push "latest" tag
     # latest tag requires submitted preflight results
     - name: Build and push
+      id: build_and_push
       uses: docker/build-push-action@v3
       with:
         context: .
@@ -178,7 +183,7 @@ jobs:
           ${{ env.IMAGE_REPOSITORY }}:latest
     
     outputs:
-      OPERATOR_HUB_IMAGE_DIGEST: ${{ steps.publish-image.outputs.digest }}
+      operator_hub_image_digest: ${{ steps.build_and_push.outputs.digest }}
 
   publish-bundle:
     name: Publish Bundle to Certified Operators
@@ -190,6 +195,13 @@ jobs:
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
+
+    - name: Check if registry secrets are set
+      run: |
+        if [ "${{ secrets.STAKATER_GITHUB_TOKEN }}" == "" ]; then
+          echo "Required Secrets 'STAKATER_GITHUB_TOKEN' is not set!"
+          exit 1
+        fi
 
     - name: Set up GO
       uses: actions/setup-go@v3
@@ -207,13 +219,6 @@ jobs:
         echo ${{ secrets.REGISTRY_REDHAT_IO_PULL_SECRET }} | base64 -d > ~/.docker/config.json
         docker login registry.redhat.io
 
-    - name: Login to Quay Registry
-      uses: docker/login-action@v2
-      with:
-        registry: quay.io
-        username: ${{ secrets.OPERATOR_HUB_USERNAME }}
-        password: ${{ secrets.OPERATOR_HUB_PASSWORD }}
-
     - name: Install CLI tools from OpenShift Mirror
       uses: redhat-actions/openshift-tools-installer@v1
       with:
@@ -222,7 +227,7 @@ jobs:
 
     - name: Update Image Digest
       env:
-        OPERATOR_HUB_IMAGE_DIGEST: ${{ steps.publish-image.outputs.digest }}
+        OPERATOR_HUB_IMAGE_DIGEST: ${{ needs.publish-image.outputs.operator_hub_image_digest }}
       run: |
         echo ${{ steps.publish-image.outputs.digest }}
         make update-operator-hub-image-digest
